stream-processor:
  pos-topic: pos_topic
  uk-shipment-topic: uk_shipment_topic
spring.cloud.stream:
  function:
    definition: hadoopRecordProcessor;notificationProcessor;shipmentProcessor
  bindings:
    shipmentProcessor-in-0:
      destination: pos_topic
    notificationProcessor-in-0:
      destination: pos_topic
    hadoopRecordProcessor-in-0:
      destination: pos_topic
    notificationProcessor-out-0:
      destination: loyalty_topic
    hadoopRecordProcessor-out-0:
      destination: hadoop_sink_topic
    shipmentProcessor-out-0:
      destination: uk_shipment_topic
  kafka:
    binder:
      applicationId: stream processor
      brokers:
        - localhost:9092
    bindings:
      shipmentProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        notificationProcessor-in-0:
          consumer:
            configuration:
              value:
                deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        hadoopRecordProcessor-in-0:
          consumer:
            configuration:
              value:
                deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        notificationProcessor-out-0:
          producer:
            configuration:
              value:
                serializer: org.springframework.kafka.support.serializer.JsonSerializer
        hadoopRecordProcessor-out-0:
          producer:
            configuration:
              value:
                serializer: org.springframework.kafka.support.serializer.JsonSerializer
        shipmentProcessor-out-0:
          producer:
            configuration:
              value:
                serializer: org.springframework.kafka.support.serializer.JsonSerializer
